### ISSUE TITLE
About page is outdated

### ISSUE THREAD

**Issue by Scheirle** [alacarte-maps/alacarte-maps.github.io#3]
The [about page](https://alacarte-maps.github.io/stories/about.html) still talks about a kd-Tree.
But we are already using a STR-Tree [1]

[1] https://alacarte-maps.github.io/posts/alacarte-0.3.0.html

**Comment by florianjacob** [comment]
Too many places to update the intro text. :laughing:
Fixed via 6df37538f13bc8c9b10381d90839d7f9d004fdf2.
