### ISSUE TITLE
Contact page is broken

### ISSUE THREAD

**Issue by Scheirle** [alacarte-maps/alacarte-maps.github.io#4]
https://alacarte-maps.github.io/stories/contact.html

```
Docutils System Messages

System Message: ERROR/3 (<string>, line 6); backlink
Unknown target name: "#alacarte on chat.freenode.net".
```

**Comment by florianjacob** [comment]
Thanks, fixed! Very useful that nothing in the deployment pipeline threw an error except the actual page. :laughing:
