### ISSUE TITLE
reduce external resources on website

### ISSUE THREAD

**Issue by florianjacob** [alacarte-maps/alacarte-maps.github.io#5]
We include javascripts etc (and fonts?, and more? check with network viewer / tracking blocker) from varous sources. It would be nice to reduce that, so that only github and ourselves can try to track our visitors. 😉

**Comment by Semoar** [comment]
Fixed with 6b770d0. Only contacted servers are now alacarte-maps.github.io (webserver), tiles.simon-dreher.de (tile server) and piwik.wolkenplanet.de (tracking)
